### PR TITLE
Add LESS option to half_pipe:install rake task

### PR DESCRIPTION
**Pull request by gbmoretti**
Hi,

Here we use Less instead Sass so I added an option in half_pipe task to generate the files (and grunt dependencies)  to work with Less.

### CODE REVIEW

**Comment by MarkMurphy** [comment]
Will someone please pull this into the master, I want this!

**Comment by gbmoretti** [comment]
You can use `gem "half-pipe", git: "git@github.com:gbmoretti/half-pipe.git", branch: "less-generator"` until they don't merge this.

**Comment by MarkMurphy** [comment]
I noticed that csso removes the source map comment needed for debugging if you try to turn on less source maps. Also, no main.less file is generated.

**Comment by gbmoretti** [comment]
I'll take a look on that. Thanks for the feedback :)

**Comment by MarkMurphy** [comment]
@gbmoretti no problem. you'll also need to update to latest grunt-contrib-less (currently 0.9.0) to get the sourceMap options for less

my less.js config file looks like this

```
module.exports = {
  debug: {
    files: {
      "<%= dirs.tmp %>/public/assets/styles/main.css": "<%= dirs.tmp %>/prepare/assets/styles/main.less"
    },
    options: {
      sourceMap: true,
      outputSourceFiles: true,
      sourceMapURL: "main.css.map",
      sourceMapFilename: "<%= dirs.tmp %>/public/assets/styles/main.css.map"
    }
  },
  "public": {
    files: {
      "<%= dirs.tmp %>/public/assets/styles/main.css": "<%= dirs.tmp %>/prepare/assets/styles/main.less"
    }
  }
};
```

**Comment by MarkMurphy** [comment]
Also just noticed that there's no support for the asset helper methods (image_url, image_path, etc...) and importing bower components as according to the README doesn't work either.

**Comment by joshwalsh** [comment]
@MarkMurphy Check to make sure you are on the latest beta.  Those should be working fine at this point.

**Comment by joshwalsh** [comment]
@MarkMurphy Sorry, looking back I misunderstood this to mean under `master` not the pull request.  They should be working on `master` with sass, but I haven't tested it on this pull request yet.

**Comment by MarkMurphy** [comment]
@joshwalsh Yep, it's LESS we're using not SASS

**Comment by joefiorini** [comment]
@MarkMurphy @gbmoretti @joshwalsh I had to write custom Sass helpers to make them work there. Perhaps we can do something similar to what `less-rails` does and register them in a `lib/half-pipe/less.rb` file (see https://github.com/metaskills/less-rails/blob/master/lib/less/rails/helpers.rb). What do you all think?

**Comment by MarkMurphy** [comment]
@joefiorini Could, but I was just thinking to myself if it might be do-able via grunt because then it wouldn't have to be specific to rails

**Comment by joefiorini** [comment]
@MarkMurphy I'm all about making Half Pipe more generic, but I also want to make sure we have sane configuration. Right now Rails allows us to give it custom asset paths and that works very nicely with all of its own view helpers and has the added bonus of allowing us to register them in stylesheet preprocessors. If we configure them in Grunt, then we'll end up with configuration in two places, which is a nightmare to understand and maintain.

**Comment by gbmoretti** [comment]
We can use the [paths](https://github.com/gruntjs/grunt-contrib-less#paths) option to configure the bower packages imports, no?

**Comment by MarkMurphy** [comment]
@joefiorini I totally agree with you, I was just thinking if we could read configuration from rails into grunt somehow, then we wouldn't have to worry about that but I realize that's starting to get a bit out of hand.

**Comment by MarkMurphy** [comment]
@gbmoretti Yes, that's a good idea. So this is what I did to get bower imports working:

 config/half-pipe.json:

```
{
  "tmp": "tmp/half-pipe",
  "bower": "bower_components"
}
```

tasks/options/less.js:

```
module.exports = {
  debug: {
    files: {
      "<%= dirs.tmp %>/public/assets/styles/main.css": "<%= dirs.tmp %>/prepare/assets/styles/main.less"
    },
    options: {
      sourceMap: true,
      outputSourceFiles: true,
      sourceMapURL: "main.css.map",
      sourceMapFilename: "<%= dirs.tmp %>/public/assets/styles/main.css.map",
      paths: ["<%= dirs.bower %>"]
    }
  },
  "public": {
    files: {
      "<%= dirs.tmp %>/public/assets/styles/main.css": "<%= dirs.tmp %>/prepare/assets/styles/main.less"
    }
  }
};
```

**Comment by joefiorini** [comment]
@MarkMurphy I believe the latest versions of the Gruntfile actually load `.bowerrc` into the configuration for you. You should already be able to say `dirs.bower`. I'll double check though.

**Comment by joefiorini** [comment]
Okay, I was half right. Take a look at https://github.com/d-i/half-pipe/blob/master/lib/generators/half_pipe/templates/Gruntfile.js#L16 and https://github.com/d-i/half-pipe/blob/master/lib/generators/half_pipe/templates/tasks/options/sass.js#4. You can say `bowerOpts.directory` and it will load from the `.bowerrc`.

**Comment by joefiorini** [comment]
The problem might be that the `.bowerrc` doesn't add the directory for you. Maybe we should add that property and default it to `bower_components`?

**Comment by MarkMurphy** [comment]
@gbmoretti Also, you'll notice I had to use the `outputSourceFiles: true` which puts the less files into the map instead of referencing them.

The source mapping was originally pointing to tmp/half_pipe/prepare/assets/main.less

@joefiorini Correct me if I'm wrong but I don't think the current setup is geared to serve up uncompiled source files.

**Comment by joefiorini** [comment]
@MarkMurphy you are correct. I've been building this to work with sourcemaps instead. You know, Sass 2.3 will be out... someday.

**Comment by MarkMurphy** [comment]
@joefiorini good to know. I'm not sure what the cleanest way to do that is just yet. But adding it in as a default won't hurt.

**Comment by MarkMurphy** [comment]
@joefiorini We should probably open another issue for this but in regards to your previous comment about: [https://github.com/metaskills/less-rails/blob/master/lib/less/rails/helpers.rb](https://github.com/metaskills/less-rails/blob/master/lib/less/rails/helpers.rb) 

Do you think that's something you could implement pretty quick? I'd really like to start using this and this is currently one thing that's preventing that from happening. We already have an established code base which uses these helper functions and I'd like to keep them in place so that should we decide to put up a CDN, it'll be a simple switch.

I'd love to help the project out anyway I can but I'm still relatively new to both ruby and rails.

**Comment by gbmoretti** [comment]
I guess now we need only the helpers methods.

**Comment by MarkMurphy** [comment]
@gbmoretti @joefiorini @joshwalsh It actually is possible to get the assets configuration from rails in a grunt task and use that to build out the asset helpers.

Here's what I have so far:

I created a rake task in my rails application `lib/assets_config.rake`:

```
namespace :assets do
  desc "Outpout rails application assets config"
  task :config => :environment do
    puts Rails.application.config.assets.to_json
  end
end
```

Then I installed grunt-shell and added the following task:

```
shell: {
  assetsConfig: {
    command: 'rake assets:config',
    options: {
      callback: function (err, stdout, stderr, cb) {
        grunt.config.set('assetsConfig', JSON.parse(stdout));
        console.log(grunt.config.get('assetsConfig'))
        cb();
      }
    }
  }
}
```

in the less options we could then begin to define our custom functions:

```
options: {
  ...
  customFunctions: {
    "image-url": function (less, arg) {
      return 'url(' + (arg.quote ? arg.quote : '"') + '/assets/images/' + arg.value + (arg.quote ? arg.quote : '"') + ')';
    }
    ...
  }
}
```

#### EDIT

replaced `.inspect` in the rake task with `.to_json`
added JSON.parse() in grunt task callback

**Comment by MarkMurphy** [comment]
The solution above would also allow you to load assets from installed gems

**Comment by joefiorini** [comment]
@MarkMurphy I appreciate you thinking about this problem. I don't think we should implement a rake task to dump the settings from Rails. Here's why:

1____projects_citizen-sync_basedemo__tmux_-4

I don't think adding 4s onto every grunt task would be beneficial. What if instead we used `config/half-pipe.json` for path configs and read that file into both Rails & Grunt? I think I had this on the roadmap for a future release. I'd certainly be willing to review PRs around it. If you want to discuss this further, let's do that in a separate issue.

**Comment by joefiorini** [comment]
@MarkMurphy I realized a problem with adding the less helpers. The grunt-contrib-less plugin does not actually run through Ruby (and rightly so), therefore what `less-rails` does is not actually an option. What I would recommend for the time being, until the path configuration issue is solved, is hard-coding the `custom functions` option in your less config after generating. Once implemented, we can update the generator to include the functions using the configured paths. It's a hack for sure, but the good news is I don't have plans to change the paths at this time.

Given that, is this ready to merge in? @gbmoretti

**Comment by gbmoretti** [comment]
For me it's ok :)

**Comment by joefiorini** [comment]
@MarkMurphy You got quiet, hope I didn't offend you along the line.

@gbmoretti I'm going to go ahead and merge this in then. Thanks for the PR!

**Comment by MarkMurphy** [comment]
@joefiorini haha, no...just thought I would stop spamming you guys with comments :)

> I don't think we should implement a rake task to dump the settings from Rails. Here's why:
> 
> I don't think adding 4s onto every grunt task would be beneficial. What if instead we used config/half-pipe.json for path configs and read that file into both Rails & Grunt? I think I had this on the roadmap for a future release. I'd certainly be willing to review PRs around it. If you want to discuss this further, let's do that in a separate issue.

While I do agree 4 seconds is a lot of overhead for this I also don't think that using the half-pipe.json will fix the issue we're trying to solve either. If you go with the half-pipe.json as the paths config then that would mean users have to manually provide the path to any resources added by gems they have installed.

Maybe there's a compromise in a mix of the two somewhere, I'm not sure but there's definitely issues with both.

Maybe we could only parse the rails config every so often. Maybe trigger some kind of check to see if the Gemfile or environment config has changed since we last ran the task to get the rails config?

**Comment by MarkMurphy** [comment]
@gbmoretti Haven't tested the updates you made but I didn't notice anything different about the csso config. Did you double check that source maps were appearing in your browser?

**Comment by gbmoretti** [comment]
@MarkMurphy  it's in the [less config](https://github.com/d-i/half-pipe/blob/master/lib/generators/half_pipe/templates/tasks/options/less.js#L5)

**Comment by MarkMurphy** [comment]
@gbmoretti yes the options to enable source maps are there but csso strips off the necessary comment that's appended to the end of main.css so the source map is never referenced. You should see something similar to this appended to the end of main.css:

```
/*# sourceMappingURL=<url> */
```

More info here [https://developers.google.com/chrome-developer-tools/docs/css-preprocessors](https://developers.google.com/chrome-developer-tools/docs/css-preprocessors)

**Comment by gbmoretti** [comment]
Ha! Of course! I tested only on 'debug' environment. Totally forgot the public, with minified stylesheets, environment
I'll take a look, thanks.

**Comment by MarkMurphy** [comment]
> I tested only on 'debug' environment

It minifies in both doesn't it?

**Comment by gbmoretti** [comment]
@MarkMurphy I opened another issue for it #64

**Pull request merged**
