### PR TITLE
Remove css minification from debug task (LESS)

### PR DESCRIPTION
**Pull request by MarkMurphy**
Fixes Issue #64

### CODE REVIEW

**Comment by gbmoretti** [comment]
Thanks @MarkMurphy  :)
How about change csso by cssmin too? I guess packages grunt-contrib-\* should be more "official" and consequently has better support.

**Comment by MarkMurphy** [comment]
@joefiorini It's tough to stay motivated to help with this project when it takes so long to have code merged. Have you thought about appointing some additional administrators?

**Comment by joefiorini** [comment]
@MarkMurphy I definitely haven't had the time to dedicate to this project that I would like. It doesn't help that I've been working mostly on apps that don't use half pipe lately. Are you volunteering? Are you on IRC or gchat?

**Comment by joefiorini** [comment]
Eventually I think it would be good to use a helper like `filterAvailableTasks` like  https://github.com/stefanpenner/ember-app-kit/blob/master/tasks/helpers.js#L31-L56. Basically, it looks at the installed NPM packages and only uses the tasks that they support.

**Pull request merged**
